[build]
  base = "."
  publish = "react-app/dist"
  command = "cd react-app && npm install && npm run build"
  functions = "../netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  publish = "dist"
  functions = "../netlify/functions"
  functionsPort = 9999
  base = "react-app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.branch-deploy]
  command = "npm run build"
  publish = "dist"
  base = "react-app"

[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[build.environment]
  NODE_VERSION = "18" 