[build]
  base = "react-app"
  command = "npm run build"
  publish = "dist"
  functions = "../netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  publish = "dist"
  functions = "../netlify/functions"
  functionsPort = 9999
  base = "react-app"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[context.branch-deploy]
  command = "npm run build"
  publish = "dist"
  base = "react-app"

[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true

[[plugins]]
  package = "@netlify/plugin-lighthouse" 