[build]
  base = "."
  publish = "react-app/dist"
  command = "cd react-app && npm install && npm run build"

[dev]
  command = "cd react-app && npm run dev"
  port = 5173
  targetPort = 5173
  publish = "react-app/dist"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[build.environment]
  NODE_VERSION = "18" 