[build]
  publish = "."
  command = "echo 'Debug: Creating config.js with values:' && echo 'Base ID: $AIRTABLE_BASE_ID' && echo 'Table Name: $AIRTABLE_TABLE_NAME' && echo 'API Key: ${AIRTABLE_API_KEY:0:5}...' && echo 'export const AIRTABLE_BASE_ID = \"$AIRTABLE_BASE_ID\"; export const AIRTABLE_API_KEY = \"$AIRTABLE_API_KEY\"; export const AIRTABLE_TABLE_NAME = \"$AIRTABLE_TABLE_NAME\";' > src/config.js"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true

[[plugins]]
  package = "@netlify/plugin-lighthouse" 