[build]
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/edge-functions/airtable-proxy/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[edge_functions]]
  path = "/.netlify/edge-functions/airtable-proxy/*"
  function = "airtable-proxy"

[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true

[[plugins]]
  package = "@netlify/plugin-lighthouse" 