[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  base = "react-app"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  publish = "dist"
  functions = "netlify/functions"
  functionsPort = 9999
  base = "react-app"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[context.branch-deploy]
  command = "npm run build"
  publish = "dist"
  base = "react-app" 