[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 