[build]
  publish = "."
  command = "printf '// This file is generated during build\nexport const AIRTABLE_BASE_ID = \"%s\";\nexport const AIRTABLE_API_KEY = \"%s\";\nexport const AIRTABLE_TABLE_NAME = \"%s\";\n' \"$AIRTABLE_BASE_ID\" \"$AIRTABLE_API_KEY\" \"$AIRTABLE_TABLE_NAME\" > src/config.js"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "src/config.js"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.images]
  compress = true

[[plugins]]
  package = "@netlify/plugin-lighthouse" 